const projects = [
    { id: 0, title: "", description: "", images: ["/images/giphy/BerqIjRJo79qKepITt.webm"] },
    { id: 1, title: "", description: "", images: ["/images/giphy/4lOcXKbyMQTHYYHBeg.webm", "/images/giphy/Fx2QfvGT2z1LWnpM4F.webm", "/images/giphy/4Bf7khDZyamqsPXqTJ.webm", "/images/giphy/tYeXaF0YNoYijlDzLv.webm"] },
    { id: 2, title: "", description: "", images: ["/images/giphy/4kUVSq7wg2AXVqi6Qy.webm", "/images/giphy/qVZjeGCtGG6QdEdW06.webm", "/images/giphy/EboO9p5uywcRlBIhcI.webm", "/images/giphy/nw76QzszddgT1zC6d2.webm"] },
    { id: 3, title: "", description: "", images: ["/images/giphy/oYEzt0WBCERnj5B53D.webm", "/images/giphy/KOUksd5twlFDRmBM67.webm"] },
    { id: 4, title: "", description: "", images: ["/images/giphy/e51EH3hjubRn93DenW.webm", "/images/giphy/HHbptUBbFr59tqyfAw.webm", "/images/giphy/kHJmYMeTjZMGma9BHx.webm"] },
    { id: 5, title: "", description: "", images: ["/images/giphy/xoiBygvrr1Wz9odify.webm", "/images/giphy/NqjfDghCnXFNBYlKjM.webm", "/images/giphy/kTDhWrgliVPPe9U8DJ.webm"] },
    { id: 6, title: "", description: "", images: ["/images/giphy/TZZFoJ2KTCKag8SHCG.webm", "/images/giphy/IaXx3aUshgmAOsv4Di.webm", "/images/giphy/cjw9Af81qWURmBaYv6.webm"] },
    { id: 7, title: "", description: "", images: ["/images/giphy/Yoyk8VjdEY3EH9DD14.webm", "/images/giphy/ozh1qmJ3YzHjpe6huO.webm"] },
    { id: 8, title: "", description: "", images: ["/images/giphy/oC9P648C0N9ULGUTmX.webm"] },
    { id: 9, title: "", description: "", images: ["/images/giphy/5jbyfzSCh7TvUbhtwU.webm", "/images/giphy/OAsvTT8ibAnkRW7uVN.webm", "/images/giphy/RANY0lmgR1O9LYX4FO.webm"] },
    { id: 10, title: "", description: "", images: ["/images/giphy/t3Ng220rBP0yQJ3VS0.webm", "/images/giphy/It6wa06m0m7NwfQr4u.webm", "/images/giphy/8zsgOKAxxXL8XA5mfH.webm"] },
    { id: 11, title: "", description: "", images: ["/images/giphy/YvioIzaF6qmxG31x7s.webm", "/images/giphy/caPgRNSIfIo3VPLF2t.webm", "/images/giphy/1NnDKWi5g5U8S678gD.webm"] },
    { id: 12, title: "", description: "", images: ["/images/giphy/xc6YQSNhP5BTfq9ArH.webm", "/images/giphy/sRKTo86gHv9j6yjEd9.webm", "/images/giphy/adcI5vcUymT55WcNmj.webm"] },
    { id: 100, title: "", description: "dark ritual slot - After Effects ( 25h )", images: ["/images/spine-animator/dr1.webm", "/images/spine-animator/dr2.webm"], isFullWidth: true },
    { id: 101, title: "", description: "levels map  -  flash (.8h )", images: ["/images/spine-animator/bhmap2.webm", "/images/spine-animator/bhmap1.webm"] },
    { id: 102, title: "", description: "", images: ["/images/spine-animator/bhfails.webm"] },
    { id: 103, title: "", description: "slot high symbol  - spine ( 8h )", images: ["/images/spine-animator/TZ_Merlin_prefinal.webm"] },
    { id: 104, title: "", description: "", images: ["/images/spine-animator/2021-03-06_04_26_59.webm"] },
    { id: 105, title: "", description: "rodeo - game item  - spine ( 6h ) ", images: ["/images/spine-animator/200.webm"] },
    { id: 106, title: "", description: "facebook game - js", images: ["/images/spine-animator/facebook.webm"] },
    { id: 107, title: "", description: "", images: ["/images/spine-animator/joyvi1.webm"], isFullWidth: true, panoramaThirds: ["/images/spine-animator/joyvi1_1.webm", "/images/spine-animator/joyvi1_2.webm", "/images/spine-animator/joyvi1_3.webm"] },
    { id: 108, title: "", description: "", images: ["/images/spine-animator/joyvipanda.webm"] },
    { id: 109, title: "", description: "", images: ["/images/spine-animator/slotoshara.webm"] },
    { id: 110, title: "", description: "", images: ["/images/spine-animator/slotoboom.webm"] },
    { id: 111, title: "", description: "", images: ["/images/spine-animator/sqbonus.webm"] },
    { id: 112, title: "", description: "", images: ["/images/spine-animator/sqheigh.webm", "/images/spine-animator/high_symbols.webm"] },
    { id: 113, title: "", description: "", images: ["/images/spine-animator/bomb_previev_05.webm", "/images/spine-animator/bomb_idle.webm"] },
    { id: 114, title: "", description: "", images: ["/images/spine-animator/strategy.webm"] },
    { id: 115, title: "", description: "", images: ["/images/spine-animator/strtgybig.webm"] },
    { id: 116, title: "", description: "", images: ["/images/spine-animator/space.webm"] },
    { id: 117, title: "", description: "", images: ["/images/spine-animator/uiface.webm"] },
    { id: 118, title: "", description: "", images: ["/vids/5ed48d46.webm"] },
    { id: 119, title: "", description: "", images: ["/vids/97d70bab.webm"] },
    { id: 120, title: "", description: "", images: ["/vids/e3f91594.webm"] },
    { id: 121, title: "", description: "", images: ["/vids/f8afd2d8.webm"] },
    { id: 122, title: "", description: "", images: ["/vids/f5133aa0.webm"] },
    { id: 123, title: "", description: "", images: ["/vids/6811a6c4.webm", "/vids/hg69a.webm", "/vids/hg69b.webm", "/vids/hg118.webm"] },
    { id: 124, title: "", description: "", images: ["/vids/76d133ac.webm"] },
    { id: 125, title: "", description: "", images: ["/vids/ce3860e0.webm"] },
    { id: 126, title: "", description: "", images: ["/vids/ddd8f8b9.webm"] },
    { id: 127, title: "", description: "", images: ["/vids/dc7a517d.webm"] },
    { id: 128, title: "", description: "", images: ["/vids/fa1c25cd.webm"] },
    { id: 129, title: "", description: "", images: ["/vids/d0333487.webm"] },
    { id: 130, title: "", description: "", images: ["/vids/450c16cf.webm"] },
    { id: 131, title: "", description: "", images: ["/vids/993c8280.webm"] },
    { id: 132, title: "", description: "", images: ["/vids/576b78c6.webm"] },
    { id: 133, title: "", description: "", images: ["/vids/08824c52.webm"] },
    { id: 134, title: "", description: "", images: ["/vids/c9fe144c.webm"] },
    { id: 135, title: "", description: "", images: ["/vids/94f3904b.webm"] },
    { id: 136, title: "", description: "", images: ["/vids/4550b17e.webm"] },
    { id: 137, title: "", description: "", images: ["/vids/af5605b9.webm"] },
    { id: 138, title: "", description: "", images: ["/vids/64a8de35.webm"] },
    { id: 139, title: "", description: "", images: ["/vids/373f35f1.webm"] },
    { id: 140, title: "", description: "", images: ["/vids/abdba791.webm"] },
    { id: 141, title: "", description: "", images: ["/vids/33b0638f.webm"] },
    { id: 142, title: "", description: "", images: ["/vids/8772c4d0.webm"] },
    { id: 143, title: "", description: "", images: ["/vids/ba564c6b.webm"] },
    { id: 144, title: "", description: "", images: ["/vids/2012360e.webm"] },
    { id: 145, title: "", description: "", images: ["/vids/0403a9b9.webm"] },
    { id: 146, title: "", description: "", images: ["/vids/912940f7.webm"] },
    { id: 147, title: "", description: "", images: ["/vids/502182b2.webm"] },
    { id: 148, title: "", description: "", images: ["/vids/2849414c.webm"] },
    { id: 149, title: "", description: "", images: ["/vids/204dddcd.webm"] },
    { id: 150, title: "", description: "", images: ["/vids/c3fd7b5d.webm"] },
    { id: 151, title: "", description: "", images: ["/vids/3d0d6cdc.webm"] },
    { id: 152, title: "", description: "", images: ["/vids/e2383a57.webm"] },
    { id: 153, title: "", description: "", images: ["/vids/5bc01eb2.webm"] },
    { id: 154, title: "", description: "", images: ["/vids/517a7add.webm"] },
    { id: 155, title: "", description: "", images: ["/vids/ad45279e.webm"] },
    { id: 156, title: "", description: "", images: ["/vids/539f0c37.webm"] },
    { id: 157, title: "", description: "", images: ["/vids/b58f30d0.webm"] },
    { id: 158, title: "", description: "", images: ["/vids/299ce7b6.webm"] },
    { id: 159, title: "", description: "", images: ["/vids/6c77473e.webm"] },
    { id: 160, title: "", description: "", images: ["/vids/f97bbf3e.webm"] },
    { id: 161, title: "", description: "", images: ["/vids/b6c41ee1.webm"] },
    { id: 162, title: "", description: "", images: ["/vids/98beb443.webm"] },
    { id: 163, title: "", description: "", images: ["/vids/36ac5820.webm"] },
    { id: 164, title: "", description: "", images: ["/vids/69198d1b.webm"] },
    { id: 165, title: "", description: "", images: ["/vids/abcdec13.webm"] },
    { id: 166, title: "", description: "", images: ["/vids/21924e5f.webm"] },
    { id: 167, title: "", description: "", images: ["/vids/345926e1.webm"] },
    { id: 168, title: "", description: "", images: ["/vids/b7736a56.webm"] },
    { id: 169, title: "", description: "", images: ["/vids/c09b36d2.webm"] },
    { id: 170, title: "", description: "", images: ["/vids/1624727c.webm"] },
    { id: 171, title: "", description: "", images: ["/vids/488f2d96.webm"] },
    { id: 172, title: "", description: "", images: ["/vids/eefe465d.webm"] },
    { id: 173, title: "", description: "", images: ["/vids/c91fbef9.webm"] },
    { id: 174, title: "", description: "", images: ["/vids/b141d6d7.webm"] },
    { id: 175, title: "", description: "", images: ["/vids/914b1733.webm"] },
    { id: 176, title: "", description: "", images: ["/vids/cdd80ee1.webm"] },
    { id: 177, title: "", description: "", images: ["/vids/0c789b30.webm"] },
    { id: 178, title: "", description: "", images: ["/vids/7d23fa7e.webm"] },
    { id: 179, title: "", description: "", images: ["/vids/6bead012.webm"] },
    { id: 180, title: "", description: "", images: ["/vids/a3979f9f.webm"] },
    { id: 181, title: "", description: "", images: ["/vids/dd31cc58.webm"] },
    { id: 182, title: "", description: "", images: ["/vids/89a2400a.webm"] },
    { id: 183, title: "", description: "", images: ["/vids/49b7f08e.webm"] },
    { id: 184, title: "", description: "", images: ["/vids/42191c0c.webm"] },
    { id: 185, title: "", description: "", images: ["/vids/2d4bc417.webm"] },
    { id: 186, title: "", description: "", images: ["/vids/7830e8d3.webm"] },
    { id: 187, title: "", description: "", images: ["/vids/379ae4aa.webm"] },
    { id: 188, title: "", description: "", images: ["/vids/3fd32b9f.webm"] },
    { id: 189, title: "", description: "", images: ["/vids/df888ea5.webm"] },
    { id: 190, title: "", description: "", images: ["/vids/a027da53.webm"] },
];

module.exports = { projects };